### ISSUE TITLE
wp-admin does not work

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-wordpress#219]
When going to https://wp.stanforddaily.com/wp-admin

It redirects me to

https://wp.stanforddaily.com/wp-login.php?redirect_to=https%3A%2F%2Fwww.stanforddaily.com%2Fwp-admin%2F&reauth=1

and then when I sign in, brings me back to the login screen.

Really, the link should be 

https://wp.stanforddaily.com/wp-login.php?redirect_to=https%3A%2F%2Fwp.stanforddaily.com%2Fwp-admin%2F&reauth=1

**Comment by sbcatania** [comment]
This no longer appears to be an issue
